// This file is auto-generated by FlutterFire CLI
// Run: flutterfire configure
// 
// To generate this file, you need to:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. Follow the prompts to setup your Firebase project
//
// For now, this is a placeholder. You'll replace this with the actual generated file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IroBFk7f7LxWMZgqxj3Bf-ypxQj5kDM',
    appId: '1:723651142882:android:cd7f3c9f4cf758a096aabb',
    messagingSenderId: '723651142882',
    projectId: 'atlas-8af9d',
    storageBucket: 'atlas-8af9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ibuDZcyv2uh1IqK7n-dsbj2RRtVPjpY',
    appId: '1:723651142882:ios:3e795cc44ef77bb796aabb',
    messagingSenderId: '723651142882',
    projectId: 'atlas-8af9d',
    storageBucket: 'atlas-8af9d.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ibuDZcyv2uh1IqK7n-dsbj2RRtVPjpY',
    appId: '1:723651142882:ios:3e795cc44ef77bb796aabb',
    messagingSenderId: '723651142882',
    projectId: 'atlas-8af9d',
    storageBucket: 'atlas-8af9d.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF54fsRbiTPWFhVkL4SBg0bzqQSO4KXpA',
    appId: '1:723651142882:web:8075352df60f0b2c96aabb',
    messagingSenderId: '723651142882',
    projectId: 'atlas-8af9d',
    authDomain: 'atlas-8af9d.firebaseapp.com',
    storageBucket: 'atlas-8af9d.firebasestorage.app',
    measurementId: 'G-VQ4RPZGH99',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF54fsRbiTPWFhVkL4SBg0bzqQSO4KXpA',
    appId: '1:723651142882:web:50ef470c1147b95096aabb',
    messagingSenderId: '723651142882',
    projectId: 'atlas-8af9d',
    authDomain: 'atlas-8af9d.firebaseapp.com',
    storageBucket: 'atlas-8af9d.firebasestorage.app',
    measurementId: 'G-PP4BPWCCMW',
  );

}